name: Deploy to EB
on:
  push:
    branches: [master]

jobs:
  buildAndTest:
    name: CI Pipeline
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend
    strategy:
      matrix:
        node-version: ['14.x']

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: ${{ env.working-directory }}
        run: npm install

      - name: Run build
        working-directory: ${{ env.working-directory }}
        run: npm run build

  deploy:
    name: CD Pipeline
    runs-on: ubuntu-latest

    env:
      working-directory: ./backend

    strategy:
      matrix:
        node-version: [ '14.x' ]

    needs: buildAndTest
    steps:
      - uses: actions/checkout@v2
      - name: Create env file
        run: |
          touch .env echo PORT=8081 >> .env
          echo NODE_ENV=${{ secrets.NODE_ENV }} >> .env
          cat .env

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: ${{ env.working-directory }}
        run: npm install

      - name: Run build
        working-directory: ${{ env.working-directory }}
        run: npm run build

      - name: Install AWS CLI 2
        working-directory: ${{ env.working-directory }}
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          which aws
          sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Generate deployment package
        working-directory: ${{ env.working-directory }}
        run: zip -r deploy.zip . -x '*.git*' './src/*' './aws/*' awscliv2.zip

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: DotoriBox
          environment_name: Dotoribox-env
          region: ${{ secrets.AWS_REGION }}
          version_label: ${{github.SHA}}
          deployment_package: ./backend/deploy.zip
